config/routes.rb
Rails.application.routes.draw do
  # get 'thanks/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'root#index'

  get 'inicio', to: 'root#inicio'

  resources :products
  resources :categories
  resources :orders do
    resources :videos, shallow: true
    resources :photos, shallow: true
    resources :fonts, shallow: true
    resources :ideas, shallow: true
    resources :phrases, shallow: true
    resources :locutions, shallow: true
  end

  get 'thanks', to: 'thanks#index'

  resources :checkout_links, only: [:create]

  get '/admin', to: redirect('/admin/session/new'), as: 'admin_root'

  namespace :admin do
    resources :categories
    resources :products
    resources :orders
    resources :locutions
    resources :faqs
    resource :session, only: [:new, :create, :destroy]
  end
end

app/views/admin/_footer.html.erb
<footer class="container py-4 mt-4 border-top">
  <div class="col-lg-6 mx-auto text-center">
    <%= link_to 'Página principal', root_path, class: 'link-secondary text-decoration-none' %>
  </div>
</footer>

app/views/admin/_header.html.erb
<header class="border-bottom mb-4">
	<!-- Default header -->
	<div class="container px-4 py-3 d-none d-md-block">
		<div class="d-flex justify-content-between align-items-center">
			<%= link_to admin_orders_path, class: 'd-flex align-items-center justify-content-start link-dark text-decoration-none' do %>
				<span class="fs-4">Átomo Digital</span>
			<% end %>
			<ul class="nav">
				<li class="nav-item"><%= link_to 'Órdenes', admin_orders_path, class: "nav-link #{params[:controller] == 'admin/orders' ? 'link-primary' : 'link-secondary'}" %></li>
				<li class="nav-item"><%= link_to 'Productos', admin_products_path, class: "nav-link #{params[:controller] == 'admin/products' ? 'link-primary' : 'link-secondary'}" %></li>
				<li class="nav-item"><%= link_to 'Categorías', admin_categories_path, class: "nav-link #{params[:controller] == 'admin/categories' ? 'link-primary' : 'link-secondary'}" %></li>
				<li class="nav-item"><%= link_to 'Locuciones', admin_locutions_path, class: "nav-link #{params[:controller] == 'admin/locutions' ? 'link-primary' : 'link-secondary'}" %></li>
				<li class="nav-item"><%= link_to 'Preguntas Frecuentes', admin_faqs_path, class: "nav-link #{params[:controller] == 'admin/faqs' ? 'link-primary' : 'link-secondary'}" %></li>
			</ul>
			<%= link_to 'Cerrar sesión', admin_session_path, method: :delete, class: 'link-danger text-decoration-none' %>
		</div>
	</div>
	<!-- Small header -->
	<div class="container px-4 py-3 d-md-none">
		<div class="d-flex justify-content-between align-items-center">
			<%= link_to admin_orders_path, class: 'd-flex align-items-center justify-content-start link-dark text-decoration-none' do %>
				<svg class="bi me-2" width="40" height="32">
					<use xlink:href="#bootstrap">
						<svg id="bootstrap" viewBox="0 0 118 94">
							<title>Logo</title>
							<path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
						</svg>
					</use>
				</svg>
				<span class="fs-4">Átomo Digital</span>
			<% end %>
			<div class="py-2 ps-4" data-bs-toggle="offcanvas" data-bs-target="#offcanvas">
				<i class="fas fa-bars fa-lg"></i>
			</div>
		</div>
	</div>
</header>
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvas">
	<div class="offcanvas-header">
		<%= link_to admin_orders_path, class: 'd-flex align-items-center justify-content-start link-dark text-decoration-none' do %>
			<svg class="bi me-2" width="40" height="32">
				<use xlink:href="#bootstrap">
					<svg id="bootstrap" viewBox="0 0 118 94">
						<title>Logo</title>
						<path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
					</svg>
				</use>
			</svg>
			<h5 class="offcanvas-title">Átomo Digital</h5>
		<% end %>
		<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
	</div>
	<div class="offcanvas-body border-top">
		<ul class="nav flex-column pb-3 mb-3 border-bottom">
			<li class="nav-item"><%= link_to 'Órdenes', admin_orders_path, class: "nav-link #{params[:controller] == 'admin/orders' ? 'link-primary' : 'link-secondary'}" %></li>
			<li class="nav-item"><%= link_to 'Productos', admin_products_path, class: "nav-link #{params[:controller] == 'admin/products' ? 'link-primary' : 'link-secondary'}" %></li>
			<li class="nav-item"><%= link_to 'Categorías', admin_categories_path, class: "nav-link #{params[:controller] == 'admin/categories' ? 'link-primary' : 'link-secondary'}" %></li>
		</ul>
		<ul class="nav flex-column pb-3 mb-3">
			<li><%= link_to 'Cerrar sesión', admin_session_path, method: :delete, class: 'nav-link link-danger' %></li>
		</ul>
	</div>
</div>