config/routes.rb
Rails.application.routes.draw do
  # get 'thanks/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'root#index'

  get 'inicio', to: 'root#inicio'

  resources :products
  resources :categories
  resources :orders do
    resources :videos, shallow: true
    resources :photos, shallow: true
    resources :fonts, shallow: true
    resources :ideas, shallow: true
    resources :phrases, shallow: true
    resources :locutions, shallow: true
  end

  get 'thanks', to: 'thanks#index'

  resources :checkout_links, only: [:create]

  get '/admin', to: redirect('/admin/session/new'), as: 'admin_root'

  namespace :admin do
    resources :categories
    resources :products
    resources :orders
    resources :locutions
    resources :faqs
    resource :session, only: [:new, :create, :destroy]
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_order, only: [:index, :new, :create]

  # GET /assets or /assets.json
  def index
  end

  # GET /assets/1 or /assets/1.json
  def show
  end

  # GET /assets/new
  def new
    @asset = Asset.new
  end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets or /assets.json
  def create
    @signed_id = params[:videos]

    @blob = ActiveStorage::Blob.find_signed(@signed_id)

    @blob.analyze

    @order.videos.attach(@blob)

    respond_to do |format|
      if @order.save
        @video = ActiveStorage::Attachment.find_by(blob_id: @blob.id)

        format.js
        format.html { redirect_to [:admin, @order], notice: "Video creado exitosamente." }
        format.json { render :show, status: :created, location: @order }
      else
        format.js
        format.html { render 'admin/orders/show', status: :unprocessable_entity }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assets/1 or /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to @asset, notice: "Asset was successfully updated." }
        format.json { render :show, status: :ok, location: @asset }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1 or /assets/1.json
  def destroy
    @video = ActiveStorage::Attachment.find(params[:id])

    @order = Order.find(@video.record_id)

    @video.purge

    respond_to do |format|
      format.js
      format.html { redirect_to [:admin, @order], notice: "Video borrado exitosamente." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:order_id])
  end

  # Only allow a list of trusted parameters through.
  def asset_params
    params.fetch(:asset, {})
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with id: 'new-video', url: order_videos_path(order), data: { remote: true } do |form| %>
  <% if order.errors[:videos].any? %>
    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(order.errors.count, "error evitó", 'errores evitaron') %> guardar este video:</h2>

      <hr>

      <ul class="mb-0">
        <% order.errors[:videos].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.file_field :videos, class: 'form-control', required: true, accept: 'video/mp4', direct_upload: true, data: { controller: 'progress' } %>
    <div class="form-text">Cada video debe estar en formato MP4 y tener dimensiones de 1920x1080. Además, puede durar hasta 10 segundos y pesar como máximo 50 MB.</div>
  </div>

  <div>
    <%= form.submit 'Añadir video', class: 'btn btn-primary mt-2', data: { disable_with: 'Añadiendo...' } %>
  </div>
<% end %>

app/views/videos/_video.erb
<div id="<%= dom_id video %>" class="col-12 col-sm-6 col-md-4 col-lg-3 mb-2" data-empty-state-target="item">
  <div role="button" data-bs-toggle="modal" data-bs-target="#video-preview-<%= dom_id video %>">
    <%= image_tag video.preview(resize_to_limit: [100, 100]).processed.image, class: 'img-thumbnail img-fluid' %>
    <div class="text-center"><strong><%= video.filename %></strong></div>
    <div class="text-center text-secondary">
      <%= video.metadata[:width].round %>x<%= video.metadata[:height].round %> • <%= number_to_human_size video.blob.byte_size %> | <%= ActiveSupport::Duration.build(video.metadata[:duration].round).inspect %>
    </div>
  </div>

  <div class="d-flex justify-content-center align-items-center">
    <%= button_to 'Borrar', video_path(video.id), method: :delete, data: { confirm: '¿Estás seguro de borrar este video?' }, class: 'btn btn-link text-decoration-none link-danger me-2' %>
    <%= link_to 'Descargar', rails_blob_path(video, disposition: 'attachment'), class: 'text-decoration-none link-primary' %>
  </div>

  <div id="video-preview-<%= dom_id video %>" data-controller="video-preview" class="modal fade" tabindex="-1" aria-labelledby="modal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><%= video.filename %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <video controls preload="auto" style="width: 100%; height: 100%;">
            <source id="video-preview-modal-src" src="<%= rails_blob_path video %>" type="video/mp4">
          </video>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" data-bs-dismiss="modal" aria-label="Close">Aceptar</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/videos/_video.html.erb
<div id="<%= dom_id video %>" class="col-12 col-sm-6 col-md-4 col-lg-3 mb-2" data-empty-state-target="item">
  <div role="button" data-bs-toggle="modal" data-bs-target="#video-preview-<%= dom_id video %>">
    <%= image_tag video.preview(resize_to_limit: [100, 100]).processed.image, class: 'img-thumbnail img-fluid' %>
    <div class="text-center"><strong><%= video.filename %></strong></div>
    <div class="text-center text-secondary">
      <%= video.metadata[:width].round %>x<%= video.metadata[:height].round %> • <%= number_to_human_size video.blob.byte_size %> | <%= ActiveSupport::Duration.build(video.metadata[:duration].round).inspect %>
    </div>
  </div>

  <div class="d-flex justify-content-center align-items-center">
    <%= button_to 'Borrar', video_path(video.id), method: :delete, remote: true, data: { confirm: '¿Estás seguro de borrar este video?', disable_with: 'Borrando...' }, class: 'btn btn-link text-decoration-none link-danger me-2' %>
    <%= link_to 'Descargar', rails_blob_path(video, disposition: 'attachment'), class: 'text-decoration-none link-primary' %>
  </div>

  <div id="video-preview-<%= dom_id video %>" data-controller="video-preview" class="modal fade" tabindex="-1" aria-labelledby="modal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><%= video.filename %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <video controls preload="auto" style="width: 100%; height: 100%;">
            <source id="video-preview-modal-src" src="<%= rails_blob_path video %>" type="video/mp4">
          </video>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" data-bs-dismiss="modal" aria-label="Close">Aceptar</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/videos/create.js.erb
{
    $('#new-video').html("<%= j render partial: 'videos/form', locals: { order: @order } %>")

    <% if @video %>
    $('#all-videos').append("<%= j render partial: 'videos/video', locals: { video: @video } %>")
    <% end %>
}

app/views/videos/destroy.js.erb
{
    $('#<%= dom_id @video %>').remove()
}

app/views/videos/edit.html.erb
<h1>Editing Asset</h1>

<%= render 'form', asset: @asset %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/videos/index.html.erb
<main class="container p-4">
  <h1>Videos de la orden <%= @order.id %></h1>

  <div class="card">
    <h2 class="card-header h5">Videos</h2>

    <div class="card-body border-bottom">
      <%= render partial: 'videos/form', locals: { order: @order } %>
    </div>

    <div class="card-body">
      <div data-controller="empty-state">
        <div data-empty-state-target="emptyState">La orden no tiene videos disponibles.</div>

        <div id="all-videos" class="row" data-controller="masonry">
          <%= render partial: 'videos/video', collection: @order.videos.filter(&:persisted?) %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/videos/new.html.erb
<h1>New Asset</h1>

<%= render partial: 'videos/form', locals: { order: @order } %>

<%= link_to 'Back', assets_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>