config/routes.rb
Rails.application.routes.draw do
  # get 'thanks/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'root#index'

  get 'inicio', to: 'root#inicio'

  resources :products
  resources :categories
  resources :orders do
    resources :videos, shallow: true
    resources :photos, shallow: true
    resources :fonts, shallow: true
    resources :ideas, shallow: true
    resources :phrases, shallow: true
    resources :locutions, shallow: true
  end

  get 'thanks', to: 'thanks#index'

  resources :checkout_links, only: [:create]

  get '/admin', to: redirect('/admin/session/new'), as: 'admin_root'

  namespace :admin do
    resources :categories
    resources :products
    resources :orders
    resources :locutions
    resources :faqs
    resource :session, only: [:new, :create, :destroy]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, uniqueness: true, if: :persisted?
  validates :description, presence: true, if: :persisted?
  validates :published, inclusion: [true, false], if: :persisted?

  belongs_to :category, optional: true

  before_validation :sync, on: :create

  def sync
    return errors.add(:vimeo_url, 'no puede estar en blanco') if vimeo_url.blank?

    return errors.add(:vimeo_url, "ya existe en otro producto") if Product.exists?(vimeo_url: vimeo_url)

    sync_vimeo

    return if errors.any?

    sync_checkout
  end

  def sync_vimeo
    response = Faraday.get("https://vimeo.com/api/oembed.json?url=#{self.vimeo_url}")

    return errors.add(:vimeo_url, 'no es una url válida') if response.status != 200

    body = JSON.parse(response.body).transform_keys(&:to_sym)

    # TODO: Add a failsafe in case Vimeo's API doesn't return what's expected

    self.name = body[:title]
    self.checkout_code = SecureRandom.alphanumeric(10)

    html = Nokogiri::HTML(body[:html])
    iframe = html.at('iframe')
    iframe['id'] = "preview-#{self.checkout_code}"
    self.preview_html = iframe.to_s

    self.description = body[:description].blank? ? 'Descripción por defecto.' : body[:description]
    self.thumbnail_url = body[:thumbnail_url]
    self.thumbnail_url_with_play_button = body[:thumbnail_url_with_play_button]
    self.published = true
  end

  def sync_checkout
    vendor_code = '251047031009'

    date = Time.now.utc.strftime '%Y-%m-%d %H:%M:%S'

    key = '?s=%mWtHCUlTdS)7~BRp'

    data = vendor_code.length.to_s + vendor_code + date.length.to_s + date

    hash = OpenSSL::HMAC.hexdigest("md5", key, data)

    response = Faraday.post('https://api.2checkout.com/rest/6.0/products',
                            {
                              "ProductCategory": "Audio & Video",
                              "ProductName": self.name,
                              "ProductCode": self.checkout_code,
                              "ProductType": "REGULAR",
                              "ProductVersion": "1.0",
                              "PurchaseMultipleUnits": false,
                              "ShortDescription": self.description,
                              "LongDescription": self.description,
                              "Enabled": true,
                              "GeneratesSubscription": false,
                              "Prices": [],
                              "PricingConfigurations": [
                                {
                                  "BillingCountries": [],
                                  "Default": true,
                                  "DefaultCurrency": "USD",
                                  "Name": "Default",
                                  "PriceType": "NET",
                                  "Prices": {
                                    "Regular": [
                                      {
                                        "Amount": 99,
                                        "Currency": "USD",
                                        "MaxQuantity": "99999",
                                        "MinQuantity": "1",
                                        "OptionCodes": []
                                      },
                                    ],
                                    "Renewal": []
                                  },
                                  "PricingSchema": "DYNAMIC"
                                }
                              ],
                              "AdditionalFields": [
                                {
                                  "Code": "format",
                                  "Enabled": true,
                                  "Label": "format",
                                  "Required": true,
                                },
                                {
                                  "Code": "length",
                                  "Enabled": true,
                                  "Label": "length",
                                  "Required": true,
                                }
                              ],
                            }.to_json, {
                              'Content-Type': 'application/json',
                              'Accept': 'application/json',
                              'X-Avangate-Authentication': "code=\"#{vendor_code}\" date=\"#{date}\" hash=\"#{hash}\""
                            })

    return errors.add(:base, 'Ocurrió un error sincronizando con 2Checkout') if response.status != 201
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /admin/products or /admin/products.json
  def index
    @products = Product.all.order(created_at: :desc)
  end

  # GET /admin/products/1 or /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products or /admin/products.json
  def create
    @product = Product.new(admin_product_create_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin, @product], notice: "Creaste un producto exitosamente." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1 or /admin/products/1.json
  def update
    respond_to do |format|
      if @product.update(admin_product_update_params)
        format.html { redirect_to [:admin, @product], notice: "Actualizaste el producto exitosamente." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1 or /admin/products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: "Borraste un producto exitosamente." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  def admin_product_create_params
    params.require(:product).permit(:vimeo_url)
  end

  def admin_product_update_params
    params.require(:product).permit(:name, :description, :category_id, :published)
  end

  def authenticate_user!
    admin_session_id = session[:current_admin_session_id]

    @admin_session = Admin::Session.find_by(id: admin_session_id)

    return if @admin_session

    respond_to do |format|
      format.html { redirect_to new_admin_session_url, notice: 'Debes iniciar sesión antes de ingresar a esta página.' }
    end
  end
end

app/controllers/products_controller.rb
# typed: false
include Pagy::Backend

class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    query = { published: true }

    if params[:category_id]
      return redirect_to root_path unless Category.exists?(params[:category_id])

      @category = Category.find(params[:category_id])

      query = query.merge({ category: @category })
    end
    
    @pagy, @products = pagy(Product.where(query).order(id: :asc))
  end

  # GET /product/1 or /product/1.json
  def show
  end

  # GET /product/new
  def new
    @product = Product.new
  end

  # GET /product/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product/1 or /product/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product/1 or /product/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:external_reference, :preview_url)
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
# typed: strict
include Pagy::Frontend
module ProductsHelper
    
end

app/views/admin/products/_form.html.erb
<%= form_with model: [:admin, product],  class: 'mt-3' do |form| %>
  <% if product.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <h4>Hubieron errores guardando este producto:</h4>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <hr>
      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.label :vimeo_url, 'URL de Vimeo', class: 'form-label' %>
    <%= form.text_field :vimeo_url, class: 'form-control' %>
    <div class="form-text">
      Las URL de Vimeo tienen una estructura como <span class="fw-bolder">https://vimeo.com/video/XXXXXXXXX</span>.
    </div>
  </div>

  <%= form.submit class: 'btn btn-primary mt-3' %>
<% end %>

app/views/admin/products/_product.html.erb
<%= link_to [:admin, product], class: 'text-decoration-none', data: { empty_state_target: 'item' } do %>
	<div class="card">
		<div class="card-body d-flex">
			<div class='card border-0 d-flex justify-content-center align-items-center' style='width: 150px; height: 150px'>
				<img height='100%' src="https://vumbnail.com/<%= product.vimeo_url.split('/').last %>.jpg">
			</div>
			<div class='d-flex flex-column'>
				<h5 class="card-title"><%= product.name %></h5>
				<div class="card-subtitle text-muted">
					<% if product.category_id? %>
						<span><%= product.category.name %></span>
					<% else %>
						<span>Sin categoría</span>
					<% end %>
				</div>
				<% if product.published %>
					<div class="card-text text-success">Publicado</div>
				<% else %>
					<div class="card-text text-danger">No publicado</div>
				<% end %>
			</div>
		</div>
	</div>
<% end %>

app/views/admin/products/index.html.erb
<%= render 'admin/header' %>

<main class="container px-4">
  <% if notice %>
    <div id="notice" class="alert alert-success alert-dismissible fade show">
      <%= notice %> <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <div>
    <%= link_to 'Crear Producto', new_admin_product_path, class: 'btn btn-primary' %>
  </div>

  <br>

  <div class="card">
    <h1 class="card-header h3">Productos</h1>

    <div class="card-body">
      <div data-controller="empty-state">
        <div data-empty-state-target="emptyState">No hay videos disponibles.</div>

        <div id="all_products" data-controller="masonry">
          <%= render partial: 'admin/products/product', collection: @products %>
        </div>
      </div>
    </div>
  </div>
</main>

<%= render 'admin/footer' %>

app/views/admin/products/new.html.erb
<%= render 'admin/header' %>

<main class="container px-4">
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>

  <div class="mb-2">
    <%= link_to '< Regresar', admin_products_path, class: 'text-decoration-none' %>
  </div>

  <h1>Nuevo Producto</h1>

  <%= render 'form', product: @product %>
</main>

<%= render 'admin/footer' %>

app/views/admin/products/show.html.erb
<%= render 'admin/header' %>

<main class="container px-4" >
  <div class="mb-4">
    <%= link_to '< Regresar', admin_products_path, class: 'text-decoration-none' %>
  </div>

  <% if notice %>
    <div id="notice" class="alert alert-success alert-dismissible">
      <%= notice %> <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <div class="card">
    <h1 class="card-header h3"><%= @product.name_in_database %></h1>
    <div class="card-body">
      <%= form_with model: @product, url: [:admin, @product] do |form| %>
        <% if @product.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <h2><%= pluralize(@product.errors.count, "error") %> evitaron guardar este producto:</h2>
            <hr>
            <ul>
              <% @product.errors.each do |error| %>
                <li><%= error.full_message %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-2">
          <%= form.label :vimeo_url, 'URL de Vimeo', class: 'form-label' %>
          <%= form.text_field :vimeo_url, class: 'form-control', disabled: true %>
        </div>

        <div class="mb-2">
          <%= form.label :checkout_code, 'Código de 2Checkout', class: 'form-label' %>
          <%= form.text_field :checkout_code, class: 'form-control', disabled: true %>
        </div>

        <div class="mb-2">
          <%= form.label :name, 'Nombre', class: 'form-label' %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="mb-2">
          <%= form.label :description, 'Descripción', class: 'form-label' %>
          <%= form.text_area :description, class: 'form-control', rows: 5 %>
        </div>

        <div class="mb-2">
          <%= form.label :category_id, 'Categoría', class: 'form-label' %>
          <%= form.select :category_id, Category.all.map { |category| [category.name, category.id] }, { prompt: 'Selecciona una categoría' }, class: 'form-select' %>
        </div>

        <div class="mb-2">
          <%= form.label :published, 'Publicado', class: 'form-label' %>
          <%= form.select :published, [['Sí', true], ['No', false]], {}, class: 'form-select' %>
        </div>

        <%= form.submit class: 'btn btn-primary mt-3' %>
      <% end %>
    </div>
    <div class="card-footer">
      <%= link_to 'Borrar producto', [:admin, @product], method: :delete, data: { confirm: '¿Estás seguro de borrar este producto?' }, class: 'text-decoration-none link-danger' %>
    </div>
  </div>

  <br>

  <div class="card">
    <h2 class="card-header h3">Prevista</h2>
    <div class="card-body">
      <% video = Nokogiri::HTML @product.preview_html.html_safe %>
      <% width = video.at('iframe')['width'] %>
      <% height = video.at('iframe')['height'] %>
      <% ratio = width == height ? '1x1' : '16x9' %>

      <div class="ratio ratio-<%= ratio %>">
        <%= @product.preview_html.html_safe %>
      </div>
    </div>
  </div>
</main>

<%= render 'admin/footer' %>